theme: minima
title: Resume
author: karina-15
email: KarinaElias55@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Resume for CS 113

# social links
github_username:  karina-15
linkedin: karina-elias-2b5649194

show_excerpts: true # set to false to remove excerpts on the homepage
